# 데이터 타입 변환 & 결측치 처리 기초

In [1]:
import pandas as pd

# 예시 데이터프레임 생성
data = pd.DataFrame({
    'A':['1', '2', '3'],
    'B':['4', '5', '6'],
    'C':['7', '8', '9']
})

data

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

### apply(pd.to_numeric)
- 선택한 여러 열에 한 번에 숫자 변환 함수를 적용한다.

In [7]:
# 데이터타입을 int로 변경
data[['A', 'B', 'C']] = data[['A', 'B', 'C']].apply(pd.to_numeric)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [6]:
pd.__version__

'3.0.3'

## Dropna()
- 결측값이 있는 행 제거
- 가장 간단하지만 데이터가 많이 삭제될 수 있어 신중하게 사용해야 한다.
- 결측치 비율이 매우 낮을 때만 권장한다.
- 기본값은 행 기준(axis=0)
- axis=1 --> 열(컬럼) 기준

In [9]:
data = pd.DataFrame({
    'A':['1', '2', '3', None],
    'B':['4', None, '5', '6'],
    'C':[None, '7', '8', '9']
})

data

     A    B    C
0    1    4  NaN
1    2  NaN    7
2    3    5    8
3  NaN    6    9

In [10]:
data.dropna()

   A  B  C
2  3  5  8

In [11]:
data_dropna = data.dropna()

data_dropna

   A  B  C
2  3  5  8

In [13]:
data_dropna_col = data.dropna(axis=1)

data_dropna_col

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

## fillna()
- 결측치를 다른 값으로 채운다.

## 결측값을 0으로 채우기
- 행이 삭제되지 않아 데이터 손실은 없지만, 0이라는 값의 실제 의미가 작용할 떄는 혼동될 수 있다.

In [14]:
data.fillna(0)

   A  B  C
0  1  4  0
1  2  0  7
2  3  5  8
3  0  6  9

In [15]:
data_fillna0 = data.fillna(0)

data_fillna0

   A  B  C
0  1  4  0
1  2  0  7
2  3  5  8
3  0  6  9

## 결측값을 평균으로 채우기 - fillna(mean())
- mean() : 평균
- 숫자형 데이터(나이, 온도, 점수 등)에서 가장 널리 쓰이는 결측치 처리 방식
- 극단적인 이상치가 있으면 평균이 왜곡될 수 있으니, 이상치 제거 후 평균을 채우는 순서가 안전하다.

In [17]:
data

     A    B    C
0    1    4  NaN
1    2  NaN    7
2    3    5    8
3  NaN    6    9

In [18]:
data_numeric = data.apply(pd.to_numeric)    # 숫자형으로 변환

data_numeric

     A    B    C
0  1.0  4.0  NaN
1  2.0  NaN  7.0
2  3.0  5.0  8.0
3  NaN  6.0  9.0

In [19]:
data_numeric.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       3 non-null      float64
 2   C       3 non-null      float64
dtypes: float64(3)
memory usage: 228.0 bytes

In [20]:
data_numeric.mean()

A    2.0
B    5.0
C    8.0
dtype: float64

In [21]:
data_numeric.fillna(data_numeric.mean())

     A    B    C
0  1.0  4.0  8.0
1  2.0  5.0  7.0
2  3.0  5.0  8.0
3  2.0  6.0  9.0

In [24]:
avg = data_numeric.mean()

avg

A    2.0
B    5.0
C    8.0
dtype: float64

In [27]:
data_numeric = data_numeric.fillna(avg)
data_numeric

     A    B    C
0  1.0  4.0  8.0
1  2.0  5.0  7.0
2  3.0  5.0  8.0
3  2.0  6.0  9.0

## 결측값을 최빈값으로 채우기

## 최빈값 : mode()
- 해당 열에서 가장 자주 나온 값들을 리스트 형태로 변환
- 최반값이 여러개여도 첫번쨰값 불러오기 --> [0]

In [29]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      str
 1   B       3 non-null      str
 2   C       3 non-null      str
dtypes: str(3)
memory usage: 228.0 bytes

In [30]:
mode_a = data['A'].mode()
mode_a

0    1
1    2
2    3
Name: A, dtype: str

In [31]:
type(mode_a)

pandas.Series

In [32]:
mode_a[0]

'1'

In [34]:
mode_b = data['B'].mode()[0]

mode_b

'4'

In [35]:
mode_c = data['C'].mode()[0]

mode_c

'7'

In [36]:
data['A'].fillna(mode_a)

0      1
1      2
2      3
3    NaN
Name: A, dtype: str

In [37]:
data.fillna(mode_b)

   A  B  C
0  1  4  4
1  2  4  7
2  3  5  8
3  4  6  9

In [38]:
data.apply(lambda x: x.fillna(x.mode()[0]))

   A  B  C
0  1  4  7
1  2  4  7
2  3  5  8
3  1  6  9

In [ ]:
# lambda 매개변수: 함수 몸통(리턴값)
f = lambda x: x + 1 # 매개변수 x에 +1을 한다.

f(2)    # 매개변수 x자리에 2가 들어갔다. -> +을 했다 -> 결과 3이 나왔다.

3

In [42]:
result = f(5)
result

6